BRONZE_SIH_COLUNAS_OBRIGATORIAS = [
    "N_AIH", "IDENT", "CNES", "MUNIC_RES", "MUNIC_MOV", "NASC", "SEXO",
    "DT_INTER", "DT_SAIDA", "DIAG_PRINC", "DIAG_SECUN", "COBRANCA",
    "CAR_INT", "DIAS_PERM", "MORTE", "VAL_TOT", "PROC_REA"
]
