x-airflow-common:
  &airflow-common
  build: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__DAGS_FOLDER=/opt/qimed/dags
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=qimed_secret_key_change_in_prod
    - PYTHONPATH=/opt/qimed
    - SALT_SECRET=qimed_dev_salt_2026
    - LAKEHOUSE_PATH=/opt/qimed/lakehouse/bronze
  volumes:
    - ./dags:/opt/qimed/dags
    - ./src:/opt/qimed/src
    - ./config:/opt/qimed/config
    - ./tests:/opt/qimed/tests
    - ./lakehouse:/opt/qimed/lakehouse
    - ./warehouse:/opt/qimed/warehouse
    - ./logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy
  dns:
    - 8.8.8.8
    - 1.1.1.1
  networks:
    - qimed-network

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - qimed-network

  airflow-init:
    <<: *airflow-common
    entrypoint:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password admin || true
    networks:
      - qimed-network

  airflow-webserver:
    <<: *airflow-common
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid /opt/airflow/airflow-webserver-monitor.pid; airflow webserver"
    restart: always
    ports:
      - "8088:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - qimed-network

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - qimed-network

networks:
  qimed-network:
    driver: bridge
