"""Initial models

Revision ID: 6334f6bb5879
Revises: 
Create Date: 2026-08-30 22:53:24.961612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6334f6bb5879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_connection_id'), 'jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_table('pipeline_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('strategy', sa.Enum('FULL_SNAPSHOT', 'TIMESTAMP', 'HIGH_WATERMARK', 'CDC', 'PARTITION', 'FILE_MANIFEST', name='ingestionstrategy'), nullable=False),
    sa.Column('last_successful_watermark', sa.String(), nullable=True),
    sa.Column('last_attempted_watermark', sa.String(), nullable=True),
    sa.Column('last_successful_run_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_state_connection_id'), 'pipeline_state', ['connection_id'], unique=False)
    op.create_index(op.f('ix_pipeline_state_id'), 'pipeline_state', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_state_pipeline_id'), 'pipeline_state', ['pipeline_id'], unique=False)
    op.create_table('upload_metadata',
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('processing_run_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index(op.f('ix_upload_metadata_upload_id'), 'upload_metadata', ['upload_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'SUCCEEDED_WITH_WARNINGS', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_run_id'), 'runs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_run_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_upload_metadata_upload_id'), table_name='upload_metadata')
    op.drop_table('upload_metadata')
    op.drop_index(op.f('ix_pipeline_state_pipeline_id'), table_name='pipeline_state')
    op.drop_index(op.f('ix_pipeline_state_id'), table_name='pipeline_state')
    op.drop_index(op.f('ix_pipeline_state_connection_id'), table_name='pipeline_state')
    op.drop_table('pipeline_state')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_connection_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
