BRONZE_SIA_COLUNAS_OBRIGATORIAS = [
    "PA_CODUNI", "PA_GESTOR", "PA_CONDIC", "PA_UFMUN", "PA_PROC_ID",
    "PA_TPFIN", "PA_NIVCPL", "PA_CIDPRI", "PA_SEXO", "PA_IDADE",
    "PA_MUNPCN", "PA_QTDPRO", "PA_QTDAPR", "PA_VALPRO", "PA_VALAPR"
]
